# Generated by Django 4.1.6 on 2023-03-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_cart_class_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.advisor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student')),
            ],
        ),
    ]
