# Generated by Django 4.1.6 on 2023-03-21 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_advisorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('catalog_num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('meet_days', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=10)),
                ('component', models.CharField(max_length=10)),
                ('credit_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.cart')),
            ],
        ),
    ]
