# Generated by Django 4.1.6 on 2023-03-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credit_cart',
        ),
        migrations.AddField(
            model_name='course',
            name='class_nbr',
            field=models.IntegerField(default=11111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='strm',
            field=models.CharField(default=1238, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=6),
        ),
    ]
