# Generated by Django 4.1.6 on 2023-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_classsearch_catalog_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.CharField(max_length=6),
        ),
    ]
