# Generated by Django 4.1.6 on 2023-03-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_schedule_classlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='student_name',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='studentID',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='class_list',
        ),
        migrations.AddField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(to='schedule.course'),
        ),
    ]
