# Generated by Django 4.1.7 on 2023-04-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_rename_student_name_cart_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorrequest',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
