# Generated by Django 4.1.6 on 2023-04-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_advisorrequest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
