# Generated by Django 4.1.6 on 2023-04-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_remove_cart_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.advisor'),
        ),
    ]
