# Generated by Django 4.1.7 on 2023-04-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_remove_cart_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default='2023-04-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default='2023-04-10'),
            preserve_default=False,
        ),
    ]
