# Generated by Django 4.1.6 on 2023-04-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_student_advisor'),
        ('schedule', '0015_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
    ]
