# Generated by Django 4.1.7 on 2023-04-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_merge_20230412_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('1', 'Winter'), ('2', 'Spring'), ('6', 'Summer'), ('8', 'Fall')], default='2', max_length=4),
        ),
    ]
