# Generated by Django 4.1.7 on 2023-04-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_schedule_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
    ]
