# Generated by Django 4.1.7 on 2023-04-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_remove_schedule_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorrequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
